# Configuration options can be accessed as
# configatron.site_name

development: &local
    site_name: MMFA
    site_namemobile: MMFA
    site_url: http://mmfa.heroku.com
    
    company_name: slashprog
    admin_email: k.sanmugam2@gmail.com
    
    support_name: sanmugam
    support_email: sanmugam@gmail.com
    
    site_envnote: Local Server

production:
    site_name: MMFA
    site_namemobile: MMFA
    site_url: http://mmfa.heroku.com
    
    company_name: slashprg
    admin_email: k.sanmugam2@gmail.com
    
    support_name: sanmugam
    support_email: sanmugam@gmail.com
    
    site_envnote: Production Server
  
staging:
  <<: *local

test:
  <<: *local
